services:
  - type: web
    name: proxy-server
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: ./
    envVars:
      - key: PROXY_ORIGIN
        sync: false
      - key: PORT
        sync: false
